### ISSUE TITLE
Background is black instead of blurred

### ISSUE THREAD

**Issue by scrouthtv** [ibhagwan/picom#15] opened 2020-10-03 13:08 UTC
Thanks for all your work in advance.

Here is a problem I've encountered when switching to this branch.
When using yshui's picom `vgit-fb376`, it looks like this:
![image](https://user-images.githubusercontent.com/23227405/94992334-a7deff80-0589-11eb-9c34-658c81b3d6b4.png)
However, with this fork, the background is black:
![image](https://user-images.githubusercontent.com/23227405/94992392-fab8b700-0589-11eb-94f2-e7a51c529807.png)

Also notice, how there is a remaining artifact of flameshot in the background of the terminals, that shouldn't be there.

### Platform
Arch Linux x86_64 5.8.12

### GPU, drivers, and screen setup
GPU: Intel Core Processor
I installed `xf86-video-intel 1:2.99.917+908+g7181c5a4-1` as well as `mesa 20.1.8-1`.
```
 ~ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics (ILK) (0x46)
    Version: 20.1.8
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 20.1.8
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.1.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

### Environment
`lightdm 1:1.30.0-4` and `i3-gaps 4.18.2-2`.
### picom version
`picom vgit-44b49`
```
**Version:** vgit-44b49

### Extensions:

* Shape: Yes
* XRandR: Yes
* Present: Present

### Misc:

* Use Overlay: Yes* Config file used: /home/lenni/.config/picom.conf

### Drivers (inaccurate):

Intel,  
```
### Configuration:
```
log-level = "info";
log-file = "/home/lenni/compton.log";
use-emwh-active-win = true;

experimental-backends = true;
backend = true;
corner-radius = 25.0;

shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-red = .05;
shadow-green = .05;
shadow-blue = .05;

blur: {
	method = "box";
	size = 4;
	background = false;
}

// for exclude read
// https://github.com/yshui/picom/blob/next/man/picom.1.asciidoc

shadow-exclude = [
	"class_g = 'Polybar'",
	"class_g = 'i3-frame'"
];

blur-background-exclude = [
	"class_g = 'Polybar'",
	"class_g = 'i3-frame'",
	"class_g = 'peek'"
];
```

**Comment by ibhagwan** [comment] 2020-10-03 14:55
Not sure why this happens, assuming the same config this shouldn’t happen, perhaps it’s time I rebase this branch on the latest yshui branch, I’ll keep you posted on this thread.

**Comment by scrouthtv** [comment] 2020-10-03 14:59
Thank you very much :)

**Comment by Maratripa** [comment] 2020-11-02 11:21
Hi, recently I insalled arch again, and I have the same problem, I tried with "kawase" and "dual_kawase" methods. I also tried running "experimental-backends = true" in the config file and also with the flag --experimental-backends in the terminal.

**Comment by ibhagwan** [comment] 2020-11-04 19:11
As I wrote in another issue reply, I’m still working on rebasing this fork, there have been lots of changes and conflicts in the rebase and I didn’t have as much time as I wanted to work on this, either way the main picom is really close to having both functionalities merged in the code (kawase blur is already in the code, [rounded corners still in a fork](https://github.com/yshui/picom/tree/round)) so pretty much whichever happens first.

**Comment by ibhagwan** [comment] 2020-12-14 20:37
It's currently being merged into the main picom branch by yshui, you can follow the work [in this pull request](https://github.com/yshui/picom/pull/558), once it's done we can revisit this issue as there have been many changes to the code since I created this fork.

**Comment by ibhagwan** [comment] 2021-02-06 01:22
I rebased the code on the latest from the main branch, can you try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

**Comment by scrouthtv** [comment] 2021-02-06 08:30
Which options do I need?
On 6d87428f:
 - With my default options (box blur x 4), it looks the same like yshui
 - With `dual_kawase` blur, I get `Blur method 'dual_kawase' is incompatible with the XRender backend. Fall back to default.`
 - With `dual_kawase` and `glx` and `--experimental-backends`, it crashes:
```
[ 02/06/2021 09:29:57.681 glx_has_extension INFO ] Found GLX extension GLX_SGI_video_sync.
[ 02/06/2021 09:29:57.681 glx_has_extension INFO ] Found GLX extension GLX_SGI_swap_control.
[ 02/06/2021 09:29:57.681 glx_has_extension INFO ] Found GLX extension GLX_OML_sync_control.
[ 02/06/2021 09:29:57.681 glx_has_extension INFO ] Found GLX extension GLX_MESA_swap_control.
[ 02/06/2021 09:29:57.681 glx_has_extension INFO ] Found GLX extension GLX_EXT_swap_control.
[ 02/06/2021 09:29:57.682 glx_has_extension INFO ] Found GLX extension GLX_EXT_texture_from_pixmap.
[ 02/06/2021 09:29:57.682 glx_has_extension INFO ] Found GLX extension GLX_ARB_create_context.
[ 02/06/2021 09:29:57.682 glx_has_extension INFO ] Found GLX extension GLX_EXT_buffer_age.
[ 02/06/2021 09:29:57.682 glx_has_extension INFO ] Found GLX extension GLX_MESA_query_renderer.
[ 02/06/2021 09:29:57.682 glx_init ERROR ] Failed to get GLX context.
[ 02/06/2021 09:29:57.682 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
```

What should I do?

**Comment by scrouthtv** [comment] 2021-02-06 08:37
EDIT:
I think it works for me with this confiuration:
```
experimental-backends = false;
backend = "glx";
blur: {
	method = "dual_kawase";
	size = 1;
	background = false;
}
corner-radius = 4;
```

And it looks sick:
![image](https://user-images.githubusercontent.com/23227405/107113291-5b207380-685e-11eb-8f68-9af602d29d56.png)
Great work!

There's another problem. I don't know about the current state of rounded corners, but I've changed my i3 config since I've been here last time to have borders (see screenshot).
Those aren't rounded. 

Other than that it looks great! Thanks for your amazing work!

**Comment by ibhagwan** [comment] 2021-02-06 15:50
> EDIT:
> I think it works for me with this confiuration:
> 
> ```
> experimental-backends = false;
> backend = "glx";
> blur: {
> 	method = "dual_kawase";
> 	size = 1;
> 	background = false;
> }
> corner-radius = 4;
> ```
> 
> And it looks sick:
> ![image](https://user-images.githubusercontent.com/23227405/107113417-1a752a00-685f-11eb-93fd-708e578c4ce1.png)
> Great work!
> 
> There's another problem. I don't know about the current state of rounded corners, but I've changed my i3 config since I've been here last time to have borders (see screenshot).
> Those aren't rounded.
> 
> Other than that it looks great! Thanks for your amazing work!

Looks great indeed!

I’m not sure what problem you’re referring to with i3 but if it’s related to the borders not being rounded that is because i3 draws its own borders which picom can’t detect, i3 users use `round-borders-rule` as a workaround.

**Comment by scrouthtv** [comment] 2021-02-06 23:23
How do I use `round-borders-rule`?

**Comment by ibhagwan** [comment] 2021-02-07 01:35
In example below from `picom.sample.conf` I instruct picom to draw a 10 pixel width border around Alacritty (use `xprop` to find your proper `class_g`), this essentially redraws the current border using the picom shader, use a number equal or close enough to your current border width for most aesthetically pleasing results.

Note that this supports only a solid, one color border, picom will sample the color from your exiting border (at around pixel 0,0 of your current window) and use that color to draw the new border.

```
round-borders-rule = [
  "10:class_g     = 'Alacritty'",
];
```

**Comment by scrouthtv** [comment] 2021-02-07 08:24
Here's another thing I noticed. On every startup the same error / warning is emitted *once*:
```
[ glx_init_dual_kawase_blur ERROR ] GLX error at line 778
```

**Comment by ibhagwan** [comment] 2021-02-07 16:26
> I'm afraid that I can't follow you. My problem is that the outer border is rounded, but the inner border isn't:
> ![image](https://user-images.githubusercontent.com/23227405/107141047-8e2e3a00-6926-11eb-9219-6ec4a8d7d30f.png)
> I tried to add round-borders-rule, but as far as I can tell, it does nothing.
> 
> Here's another thing I noticed. On every startup the same error / warning is emitted _once_:
> 
> ```
> [ glx_init_dual_kawase_blur ERROR ] GLX error at line 778: GL_INVALID_ENUM
> ```

First I can see you have a typo in your config, in your `round-borders-rule` you entered `class_i` where it should be `class_g`.

Second, are you sure Termite is using the `WM_CLASS` "Termite"? You can verify that if you look at the output of xprop and take the second term from the `WM_CLASS` line, here's an example from my xprop output of Alacritty (sometimes the first and second terms differ, use the second one):

```
...
WM_CLASS(STRING) = "Alacritty", "Alacritty"
...
```
Another way to verify you have the correct `class_g` is to try to exclude Termite from being rounded and check if the rule below works, if your Termite isn't rounded using this, the borders rule should work as well.

```
rounded-corners-exclude = [
  "class_g     = 'Termite'",
];
```

As for the `GL_INVALID_ENUM` error, can you post your complete `picom.conf` so I can test it myself (the error doesn't show in my machine/config)?

Also, what happens if you use `experimental-backends = true;` in your config? it should definitely make the error disappear as it uses a different code path but it might also help with the borders as it's also a different rounding code.

**Comment by scrouthtv** [comment] 2021-02-07 18:07
> First I can see you have a typo in your config, in your round-borders-rule you entered class_i where it should be class_g.

Looks like I confused the two. Backstory is that I wrote a little script that changes the first value of `WM_CLASS` (should be the instance?) every time I open vim / something else so I can have a different icon in my bar for terminal & editor in terminal.

So for picom to round the borders of both terminal & editor in terminal I had to use the second value of `WM_CLASS` (the group name? class name?) and mixed the two values up.
Looks like the only issue after all was that I was entirely missing `round-borders = 1;` in my `picom.conf`.

> As for the GL_INVALID_ENUM error, can you post your complete picom.conf so I can test it myself (the error doesn't show in my machine/config)?

For readability's sake, I'll open another issue.

> Also, what happens if you use experimental-backends = true; in your config? it should definitely make the error disappear as it uses a different code path but it might also help with the borders as it's also a different rounding code.

With `backend = "glx";` picom crashes:
```
[ 02/07/2021 19:05:31.956 reset_enable INFO ] picom is resetting...
[ 02/07/2021 19:05:32.044 glx_init ERROR ] Failed to get GLX context.
[ 02/07/2021 19:05:32.044 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
```

With `backend = "xrender";` everything is bugged:
![image](https://user-images.githubusercontent.com/23227405/107155243-a5e1de80-6977-11eb-87e8-1ac73fb65e19.png)

With backend unset, it's the same as with xrender.

**Comment by ibhagwan** [comment] 2021-02-07 18:40
> > First I can see you have a typo in your config, in your round-borders-rule you entered class_i where it should be class_g.
> 
> Looks like I confused the two. Backstory is that I wrote a little script that changes the first value of `WM_CLASS` (should be the instance?) every time I open vim / something else so I can have a different icon in my bar for terminal & editor in terminal.
> 
> So for picom to round the borders of both terminal & editor in terminal I had to use the second value of `WM_CLASS` (the group name? class name?) and mixed the two values up.
> Looks like the only issue after all was that I was entirely missing `round-borders = 1;` in my `picom.conf`.
> 
> > As for the GL_INVALID_ENUM error, can you post your complete picom.conf so I can test it myself (the error doesn't show in my machine/config)?
> 
> For readability's sake, I'll open another issue (#25).
> 
> > Also, what happens if you use experimental-backends = true; in your config? it should definitely make the error disappear as it uses a different code path but it might also help with the borders as it's also a different rounding code.
> 
> With `backend = "glx";` picom crashes:
> 
> ```
> [ 02/07/2021 19:05:31.956 reset_enable INFO ] picom is resetting...
> [ 02/07/2021 19:05:32.044 glx_init ERROR ] Failed to get GLX context.
> [ 02/07/2021 19:05:32.044 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
> ```
> 
> With `backend = "xrender";` everything is bugged:
> ![image](https://user-images.githubusercontent.com/23227405/107155243-a5e1de80-6977-11eb-87e8-1ac73fb65e19.png)
> (background is gone, transparency does not work at all, borders stay on the screen)
> 
> With backend unset, it's the same as with xrender.

So is it fair to assume everything works to your liking with `experimental-backends = false;`?

Now regarding the other issues when set to `true` let's try and isolate the offending code:

- Did you ever try official picom (by yshui) with `experimental-backends = true;` and the different backends?
- What happens when you use `corner-radius = 0;` and `method = "none";` under blur with both `glx` and `xrender` backends?

The above will help us determine if your machine has a different issue with mainline picom or with the pieces of code I added.

If you're happy with the results without the experimental-backends and wish to not troubleshoot this issue further that's ok too.

**Comment by scrouthtv** [comment] 2021-02-07 21:27
> So is it fair to assume everything works to your liking with experimental-backends = false;?

Yes.

> Did you ever try official picom (by yshui) with experimental-backends = true; and the different backends?

On 3680d32 and this config file
```
log-level = "info";
log-file = "/home/lenni/compton.log";

experimental-backends = true;
backend = "glx";
vsync = false;
//refresh-rate = 60;
unredir-if-possible = false;

corner-radius = 0;

shadow = true;
shadow-radius = 8;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-red = .05;
shadow-green = .05;
shadow-blue = .05;

blur: {
	method = "none";
	size = 0;
	background = false;
}

// for exclude read
// https://github.com/yshui/picom/blob/next/man/picom.1.asciidoc

shadow-exclude = [
	"class_g = 'i3-frame'",
	"class_i = 'tray'"
];

blur-background-exclude = [
	"class_g = 'i3-frame'",
	"class_g = 'peek'",
	"class_g = 'Google-chrome-unstable'"
];

opacity-rule = [
	"92:class_g = 'MuPDF'"
];
```

 - `glx` works as expected (picom works)
 - `xrender` works also as expected (no leftover borders, I can see the background)

**Comment by ibhagwan** [comment] 2021-02-08 01:16
> > So is it fair to assume everything works to your liking with experimental-backends = false;?
> 
> Yes.
> 
> > Did you ever try official picom (by yshui) with experimental-backends = true; and the different backends?
> 
> On [3680d32](https://github.com/ibhagwan/picom/commit/3680d323f5edf2ef5f21ab70a272358708c87a22) and this config file
> picom.conf
> 
>     * `glx` works as expected (picom works)
> 
>     * `xrender` works also as expected (no leftover borders, I can see the background)

What happens when you run this fork with `corner-radius = 0;` and `method = "none";` (code paths should be pretty much equal to mainline with these options)?

**Comment by scrouthtv** [comment] 2021-02-08 08:40
On 6d87428f with `corner-radius = 0` and `method = "none"`:
 - `glx` does not start at all (I think it crashes on launch), log file attached
<details>
<summary>Log file</summary>

```
 - `xrender` works perfectly fine as in mainline.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_SGI_video_sync.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_SGI_swap_control.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_OML_sync_control.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_MESA_swap_control.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_EXT_swap_control.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_EXT_texture_from_pixmap.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_ARB_create_context.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_EXT_buffer_age.
[ 02/08/2021 09:39:01.406 glx_has_extension INFO ] Found GLX extension GLX_MESA_query_renderer.
[ 02/08/2021 09:39:01.406 glx_init ERROR ] Failed to get GLX context.
[ 02/08/2021 09:39:01.406 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
```
</details>

**Comment by ibhagwan** [comment] 2021-02-09 02:41
Ok, so if I'm getting this right we have two different issues here (limited to `experimental-backends = true;`):
(1) xrender has an issue with border smearing **only when enabling rounded corners**
(2) unable to start picom with `backend = glx` no matter what options are used

Regarding (1): I was able to reproduce this issue and will work on fixing it.

Regarding (2): I'm so very confused what is happening with the `glx` backend... the error you're seeing is from [line #318 in glx.c](https://github.com/ibhagwan/picom/blob/6d87428f78a46bea295e0a21d23c4b56133aadc3/src/backend/gl/glx.c#L318) before the init of both blur and rounded corners and I can't find any other code I added that might cause the `glXCreateContextAttribsARB` to fail.

Can we reassess the entire `experimental-backends` situation, would you be able to run these commands on both mainline picom and my latest fork and let me know which works and which doesn't and the corresponding error messages?

```
picom --config /dev/null --experimental-backends --backend glx
picom --config /dev/null --experimental-backends --backend glx --blur-method dual_kawase
```

This eliminates rounded corners completely from the equation and since the dual_kawase code on the experimental branch is euqal in both my fork and mainline picom it should give us a better idea what's going on here (or confuse me even more if mainline works and mine doesn't lol).

**Comment by ibhagwan** [comment] 2021-02-09 06:03
Ok quick update regarding (1), I solved the bug and force-pushed the repo (cleaner single commit), rounded corners on `xrender` should not smear the borders anymore, you can test it with the following (default backend is `xrender` so backend doesn't need to be specified:

```
picom --config /dev/null --experimental-backends --corner-radius 25.0
```

**Comment by scrouthtv** [comment] 2021-02-09 14:48
> (1) xrender has an issue with border smearing only when enabling rounded corners

Yes.
> (2) unable to start picom with backend = glx no matter what options are used

Yes.

> would you be able to run these commands on both mainline picom

all three test cases crash with this error message:
```
[ 02/09/2021 15:43:16.240 glx_init ERROR ] Failed to get GLX context.
[ 02/09/2021 15:43:16.240 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
```

> rounded corners on xrender should not smear the borders anymore

Yes. Looks perfectly fine - no more smearing and the background is now also visible!

**Comment by ibhagwan** [comment] 2021-02-09 15:03
> > (1) xrender has an issue with border smearing only when enabling rounded corners
> 
> Yes.
> 
> > (2) unable to start picom with backend = glx no matter what options are used
> 
> Yes.
> 
> > would you be able to run these commands on both mainline picom
> 
> all three test cases crash with this error message:
> 
> ```
> [ 02/09/2021 15:43:16.240 glx_init ERROR ] Failed to get GLX context.
> [ 02/09/2021 15:43:16.240 initialize_backend FATAL ERROR ] Failed to initialize backend, aborting...
> ```
> 
> > rounded corners on xrender should not smear the borders anymore
> 
> Yes. Looks perfectly fine - no more smearing and the background is now also visible!

Ok, we got some progress :)

As for the crash, if the commands also fail on mainline picom it confirms my suspension that the crash is unrelated to the code I added and the issue will have to be resolved in the main branch.

**Closed** 2021-02-09 17:24 UTC
