### ISSUE TITLE
Having rounded corners causes lags overtime

### ISSUE THREAD

**Issue by DarkReaper231** [ibhagwan/picom#8] opened 2020-08-26 22:27 UTC
I can't really explain it. Maybe it is somehow just with my setup. But basically I have Manjaro i3, polybar and this fork of compton and after opening multiple windows it starts to lag as hell. Not that CPU or RAM usage would be high. For example compton-tryone-git works fine with all the settings I have, I added only one setting using this one and it is corners and it lags so I am pretty sure it is caused by something in this fork. I dont get any errors tho. Maybe it is some problem with rendering.

**Comment by ibhagwan** [comment] 2020-08-28 00:54
There was another user of i3 reporting potentially similar issues with the borders causing lags, I suspect this has to do something with the way i3 draws it's borders.

Can you please post your `picom.conf` perhaps we can work around it by changing some of the options like `--experimental-backends` and few others.

**Comment by DarkReaper231** [comment] 2020-08-28 11:34
[compton.txt](https://github.com/ibhagwan/picom/files/5141819/compton.txt)
This is my config

**Comment by thexavier666** [comment] 2020-08-29 22:23
I have the same issue. 
This lag is very visible when using [cava](https://github.com/karlstav/cava)
I'm using i3-gaps

**Comment by DarkReaper231** [comment] 2020-08-30 17:52
So I have been testing this further and figured out that the memory drain happens even when I have only round corners enabled. Like when I leave only that single line in config it still happens. The thing is tho that it happens after way longer time. So depending on how much features of picom you use the sooner it happens. Like when I only enable corners it still happens after long coding sessions.

**Comment by Afonsocraposo** [comment] 2020-09-07 09:36
I am also experiencing this problem with bspwm using gaps

**Comment by psamim** [comment] 2020-11-08 19:22
Check how much memory Xorg uses. I am experiencing the same issue. Whenever I feel the lag, I see Xorg is using above 1GB of memory! I am not sure how the compositor can cause Xorg use this much memory.

**Comment by itsNaz** [comment] 2020-11-09 16:34
Just jumping in to say that this also happens to me. Running Openbox (but this happened in KDE5 Plasma as well), and when it happens, it usually causes my windows to lag and suddenly go blank and white. Logging out solves the issue, as well as typing `kill picom && picom -b` and then `picom -b` again. Memory leak seems likely.

**Comment by joaopauloalbq** [comment] 2020-11-09 21:57
**Debug-level log output obtained right after lag**
[picom.log](https://github.com/ibhagwan/picom/files/5513436/picom.log)

**My config**
[picom.txt](https://github.com/ibhagwan/picom/files/5513444/picom.txt)

**More info**
```
Manjaro
Awesome WM 4.3-2
picom-ibhagwan-git 1383_Next.102.g44b4970_2020.08.03-1
```

**Comment by ibhagwan** [comment] 2021-02-06 01:25
I rebased the code on the latest from the main branch, can you try using the latest code from [next-rebase](https://github.com/ibhagwan/picom/tree/next-rebase)?

**Comment by thexavier666** [comment] 2021-02-17 14:50
@ibhagwan 

I have been using it for a few hours, looks like the issue is fixed. I will let you know if there are any degradations.

**Comment by ibhagwan** [comment] 2021-02-17 21:01
> @ibhagwan
> 
> I have been using it for a few hours, looks like the issue is fixed. I will let you know if there are any degradations.

That's great! tysm for the update, I'll close the issue for now.

**Closed by ibhagwan** 2021-02-17 21:01 UTC

**Comment by DarkReaper231** [comment] 2021-02-18 18:55
Yes it seems to be working much better now
